// Generated by Copilot
import Script from "next/script";

interface GoogleAddSenseProps {
  p_id?: string;
}

const GoogleAddSense: React.FC<GoogleAddSenseProps> = ({
  p_id = process.env.NEXT_PUBLIC_ADSENSE_CLIENT,
}) => {
  return (
    <Script
      async
      src={`https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=${p_id}`}
      crossOrigin="anonymous"
      strategy="afterInteractive"
    />
  );
};

export default GoogleAddSense;
